'use strict';

// Telegram bildirim üreticilerinin tek, kullanıcıya dönük kataloğu.
// Burada token veya kanal kimliği tutulmaz; yalnız env anahtarlarının adları vardır.
const COMMON_SIGNAL_CHANNELS = ['TELEGRAM_FOREX_CHANNEL', 'TELEGRAM_SIGNAL_CHANNEL'];

module.exports = Object.freeze([
  {
    id: 'forex-signals',
    name: 'Forex Sinyalleri',
    category: 'Forex',
    description: 'Forex, metal, endeks ve kripto pozisyon açılış/kapanış bildirimleri.',
    disableEnv: 'FOREX_PUSH_DISABLED',
    channelEnvs: COMMON_SIGNAL_CHANNELS,
    schedule: 'Forex taramasıyla birlikte',
  },
  {
    id: 'pro-robot',
    name: 'Pro Robot',
    category: 'Forex',
    description: 'Derin konfluanslı yeni robot sinyalleri ve pozisyon yönetim güncellemeleri.',
    disableEnv: 'PRO_PUSH_DISABLED',
    channelEnvs: COMMON_SIGNAL_CHANNELS,
    schedule: 'Pro taramayla birlikte',
  },
  {
    id: 'gold-signals',
    name: 'Altın Sinyalleri',
    category: 'Emtia',
    description: 'Çoklu zaman dilimi altın kurulumu, kapanış ve yön değişimi bildirimleri.',
    disableEnv: 'ALTIN_PUSH_DISABLED',
    channelEnvs: COMMON_SIGNAL_CHANNELS,
    schedule: 'Altın taramasıyla birlikte',
  },
  {
    id: 'beast-signals',
    name: 'Beast Trend',
    category: 'Deneysel',
    description: 'Zero-Lag, Ichimoku ve Scalper Beast birleşik sinyalleri.',
    disableEnv: 'BEAST_PUSH_DISABLED',
    channelEnvs: COMMON_SIGNAL_CHANNELS,
    schedule: 'Beast taramasıyla birlikte',
    defaultEnabled: false,
    enabledValue: '0',
    disabledValue: '1',
  },
  {
    id: 'mt5-scanner',
    name: 'MT5 Gün İçi Tarayıcı',
    category: 'MT5',
    description: 'Dokuz enstrümanın çoklu zaman dilimi gün içi sinyalleri ve günlük raporu.',
    disableEnv: 'MT5_PUSH_DISABLED',
    channelEnvs: ['TELEGRAM_MT5_CHANNEL', ...COMMON_SIGNAL_CHANNELS],
    schedule: 'Her dakika',
  },
  {
    id: 'crypto-signals',
    name: 'Kripto Sinyalleri',
    category: 'Kripto',
    description: 'Seçili kripto paritelerinin açılış ve kapanış bildirimleri.',
    disableEnv: 'CRYPTO_PUSH_DISABLED',
    channelEnvs: COMMON_SIGNAL_CHANNELS,
    schedule: 'Kripto taramasıyla birlikte',
  },
  {
    id: 'mtf-confluence',
    name: 'MTF Konfluans',
    category: 'Kripto',
    description: 'Güçlü çoklu zaman dilimi yön değişimi ve yeni fırsat bildirimleri.',
    disableEnv: 'MTF_PUSH_DISABLED',
    channelEnvs: ['TELEGRAM_MTF_CHAT_ID', ...COMMON_SIGNAL_CHANNELS],
    schedule: 'MTF kapanışlarında',
  },
  {
    id: 'bist-signals',
    name: 'BIST Sinyalleri',
    category: 'BIST',
    description: 'Kalite eşiğini geçen BIST sinyalleri ve sonuç bildirimleri.',
    disableEnv: 'BIST_SIGNAL_PUSH_DISABLED',
    channelEnvs: ['TELEGRAM_BIST_CHANNEL'],
    schedule: 'BIST seansında',
  },
  {
    id: 'crossover',
    name: 'Kesişim Tarayıcı',
    category: 'BIST',
    description: 'EMA/TEMA kesişim taramalarının yeni sonuç bildirimleri.',
    disableEnv: 'CROSSOVER_PUSH_DISABLED',
    channelEnvs: ['TELEGRAM_CROSSOVER_CHANNEL'],
    schedule: 'Kapanmış mumlarda',
  },
  {
    id: 'tema34',
    name: 'TEMA34 Tarayıcı',
    category: 'BIST',
    description: 'TEMA34 kırılımı, yeni giriş ve kapanış bildirimleri.',
    disableEnv: 'TEMA34_SCANNER_DISABLED',
    channelEnvs: ['TELEGRAM_TEMA34_CHANNEL'],
    schedule: '4 saatlik ve günlük',
  },
  {
    id: 'bist-buy-scanner',
    name: 'BIST AL Tarayıcı',
    category: 'BIST',
    description: 'BIST hisselerinde yeni AL kurulumu ve kapanış bildirimleri.',
    disableEnv: 'BIST_AL_SCANNER_DISABLED',
    channelEnvs: ['TELEGRAM_BIST_AL_CHANNEL'],
    schedule: 'BIST seansında',
  },
  {
    id: 'wave-scan',
    name: 'Dalga Tarayıcı',
    category: 'Tarama',
    description: 'Dalga yapısı sinyalleri ve takip edilen kurulum kapanışları.',
    disableEnv: 'WAVESCAN_PUSH_DISABLED',
    channelEnvs: COMMON_SIGNAL_CHANNELS,
    schedule: 'Tarama döngüsünde',
  },
  {
    id: 'news-warning',
    name: 'Haber Uyarıları',
    category: 'Koruma',
    description: 'Yüksek etkili ABD/FTMO haberlerinden önce zamanlanmış uyarılar.',
    disableEnv: 'NEWS_WARNING_DISABLED',
    channelEnvs: ['TELEGRAM_NEWS_CHANNEL', ...COMMON_SIGNAL_CHANNELS, 'TELEGRAM_CHAT_ID'],
    schedule: 'Her dakika',
  },
  {
    id: 'nr7-shadow',
    name: 'NR7 Gölge',
    category: 'Deneysel',
    description: 'NR7 gölge gözlem sonuçlarını bildiren deneysel tarayıcı.',
    disableEnv: 'NR7_SHADOW_PUSH_DISABLED',
    channelEnvs: COMMON_SIGNAL_CHANNELS,
    schedule: 'Gölge tarama döngüsünde',
  },
  {
    id: 'ict-fvg',
    name: 'ICT / FVG Akışı',
    category: 'ICT',
    description: '4 saatlik yön, 1 saatlik yapı ve kapanmış 5 dakikalık FVG teyidiyle üretilen paper işlem bildirimleri.',
    disableEnv: 'ICT_FVG_PUSH_DISABLED',
    channelEnvs: ['TELEGRAM_ICT_FVG_CHANNEL', ...COMMON_SIGNAL_CHANNELS],
    schedule: 'Her 5 dakikada, yalnız kapanmış mumlarda',
  },
  {
    id: 'account-report',
    name: 'MT5 Kâr/Zarar Raporu',
    category: 'MT5',
    description: 'Broker hesabı gerçekleşen kâr/zarar ve günlük özet bildirimleri.',
    disableEnv: 'PNL_REPORT_DISABLED',
    channelEnvs: ['TELEGRAM_PNL_CHANNEL', ...COMMON_SIGNAL_CHANNELS],
    schedule: 'Raporlayıcı tetiklediğinde',
  },
]);
